name : Tester

on:
  push:
    branches: ['main']

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo code
      uses: actions/checkout@v4

    - name: Setting up python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13.5"

    - name: Installing pytest
      run: pip install pytest

    - name: Running pytest
      run: pytest
